/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    'IAntDesign:calendarTwotone': typeof import('~icons/ant-design/calendar-twotone')['default']
    'IBi:book': typeof import('~icons/bi/book')['default']
    'ICarbon:tagGroup': typeof import('~icons/carbon/tag-group')['default']
    'IEp:timer': typeof import('~icons/ep/timer')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PostItem: typeof import('./src/components/PostItem.vue')['default']
    PostWrapper: typeof import('./src/components/PostWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}
