// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IAntDesign:calendarTwotone': typeof import('~icons/ant-design/calendar-twotone')['default']
    'IBi:book': typeof import('~icons/bi/book')['default']
    'IFluent:timer24Filled': typeof import('~icons/fluent/timer24-filled')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PostItem: typeof import('./components/PostItem.vue')['default']
    PostWrapper: typeof import('./components/PostWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
  }
}
